# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mordor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identifier',
            field=models.CharField(default='8322db97', max_length=8, verbose_name='Identifier'),
        ),
    ]
